### ISSUE TITLE
Named Types

### ISSUE THREAD

**Issue by felixangell** [ark-lang/ark-rfcs#7]
Similar to Go, we could have named types that introduce a new type. These would be safer than aliases, because it's a separate entity.

A named type is introduced with the `type` keyword, following a name (identifier), and a type. For instance:

```go
type PersonID s32;

type Person struct {
     x: PersonID,
};

type PersonGender enum {
     Male,
     Female
}
```

This also means you can have anonymous types:

```go
struct {
    a: int,
    b: s8
}
```

**Comment by kiljacken** [comment]
:+1: This would also allow further simplification of the parser/grammar

**Comment by felixangell** [comment]
Could work nicely with this issue too
https://github.com/ark-lang/ark/issues/429

**Comment by raoulvdberge** [comment]
:+1: are we gonna remove old struct decl syntax in favor for this?

**Comment by MovingtoMars** [comment]
@raoulvdberge Yeah, it would be nice.

**Comment by vnev** [comment]
:+1:

**Comment by felixangell** [comment]
Looks like this is approved, going to move over to implementation issue on ark repo.

**Comment by MovingtoMars** [comment]
I think comparison should work like this:

## Comparison
Two types can be matched if one of these conditions are met:
- one type is anonymous and both have matching layouts
- both types are anonymous and both have matching layouts
- both are the same type, from the same type definition
